### ISSUE TITLE
Comparison with htop

### ISSUE THREAD

**Issue by adrian-gierakowski** [walles/px#111]
Would be nice to add a section to the Readme comparing with [htop](https://htop.dev/)

thanks!

**Comment by walles** [comment]
This might be a good idea, but could you elaborate on why *you* want this comparison?

What would you personally get out of it?

**Comment by adrian-gierakowski** [comment]
I am a user of htop. A comparison like this would help me decide if I should give ptop a go.

**Comment by walles** [comment]
Currently there's a screenshot and a list of features at the top of the README:
https://github.com/walles/px#ptop

What about if I add a line to there saying something like "If you're coming from `htop` or some other `top` implementation, here's what to expect:"?

Would that have helped you?

This is meant to be a useful list of features, but if people are searching that page for `htop` and `htop` is not on that page then maybe people simply don't find that list + screenshot.

Or, is there some obvious outage in that list striking you as an `htop` user?

**Comment by adrian-gierakowski** [comment]
> What about if I add a line to there saying something like "If you're coming from htop or some other top implementation, here's what to expect:"?

> Would that have helped you?

Yes, that would be useful

**Comment by walles** [comment]
Thanks for bringing this up @adrian-gierakowski and for having the conversation with me!

I think the updated README is better than before.

**Comment by adrian-gierakowski** [comment]
Oh, I thought you’d be adding a new section with list of features as compared to htop. I still don’t know if, for example, ptop supports interactive proces serach\filtering like htop does :)

**Comment by walles** [comment]
I added another bullet point at the bottom of the features list:

> * A help text on the bottom hints you how to search / filter (interactively), change sort order or how to pick processes for further inspection or killing.

Are there any other features you'd like to see listed?

Since I'm not using `htop` myself it's hard for me to know what an `htop` user might want to know, so your input is super valuable @adrian-gierakowski!

**Comment by adrian-gierakowski** [comment]
Thanks! These are the features I use the most. Looks like I should give ptop a try!
