### ISSUE TITLE
use python2 for python 2

### ISSUE THREAD

**Issue by lesmana** [walles/px#25]
the script `set-py2-p3.sh` tries to determine the executables for python 2 and python 3. for python 2 it assumes that `python` is the executable. that is wrong at least for arch linux where `python` points to `python3`.

https://github.com/walles/px/blob/946d833f29a934597cc2407184b409fedbecb7ff/scripts/set-py2-p3.sh#L11

the official python recommendation is to use `python2` for python 2 and `python3` for python 3.

https://www.python.org/dev/peps/pep-0394/

**Comment by walles** [comment]
I agree, thanks for the docs link!

Will you do a PR?

**Comment by walles** [comment]
It struck me that I *might* have to clarify something here.

The final `px.pex` that is downloadable from <https://github.com/walles/px/releases/latest> is designed to work both on Python 2 and Python 3. And if it doesn't, that's a bug that needs fixing.

So, just like they recommend in the link you provided, the shebang line for this 2-or-3 Python program is `python`.

The `set-py2-p3.sh` *is* broken though when developing on a system where `python` refers to a Python 3 VM. For this problem I have an idea; I'm going to make a PR for this.

**Comment by lesmana** [comment]
i was just going to ask about this assertion in `ci.sh`
```
 if ! head -n1 px.pex | grep -w python ; then
```
https://github.com/walles/px/blob/4666707bdac8b2353cf22fa0674d64cb7804bae4/ci.sh#L23

i noticed that assertion from the output of travis from my previous pull request #27 
https://travis-ci.org/walles/px/jobs/244660297#L1436

now i understand. you want to provide one binary for linux and macosx and for python 2 and 3. using the executable `python` is correct then according to official python recommendation.

i will leave fixing this to you.

the test and install and ci scripts are quite convoluted. i see some lines appear to me as troublesome. maybe i will delve into them later.
