### ISSUE TITLE
Asked to report last line: mosh

### ISSUE THREAD

**Issue by norbusan** [walles/px#48]
Hi,

thanks for the very useful program. I just got the following message when running `px <PID-OF-MY-SESSION>`:
```
Users logged in when cinnamon-session(2417) started:
WARNING: Please report unmatched last line at https://github.com/walles/px/issues/new: <norbert  pts/3        mosh [29846]     Wed Oct 24 15:33 - 15:34  (00:01)>
WARNING: Please report unmatched last line at https://github.com/walles/px/issues/new: <norbert  pts/1        mosh [14332]     Tue Sep 11 15:28 - 15:29  (00:01)>
  norbert from :0
```

This is on Debian/unstable, `px --version` returns `0.0.0`, and the Debian package version is `1.0.13-2`.

**Comment by walles** [comment]
@norbusan, this was a school book example on how to report bugs.

Thanks!

**Comment by norbusan** [comment]
@walles Hahaha, good joke! Thanks for fixing. Most bugs need much more time to report than this one, with backtraces, code analysis etc.

Thanks for the nice program!
