### ISSUE TITLE
ptop: "ResourceWarning: unclosed file"

### ISSUE THREAD

**Issue by jensgreen** [walles/px#57]
I'm getting this error at the bottom of the window for a split second on every `ptop` tick:

![screenshot 2019-02-08 at 11 10 55](https://user-images.githubusercontent.com/2438597/52472053-b269ab80-2b92-11e9-860d-a7cee12f920f.png)

Using Python 3.6.5 and zsh.

**Comment by walles** [comment]
Well spotted Jens!

Unable to repro but most likely fixed in 1.0.19.
