### ISSUE TITLE
px <PID> shows strange time usage

### ISSUE THREAD

**Issue by norbusan** [walles/px#77]
First of all, thanks for the very useful program. I don't really have any complaint, just realized today when checking a long running btrfs balance job that the used time is **slightly** off:
```
# px 4496
btrfs
...
4h49m ago btrfs was started, at 2020-05-25T14:23:28+09:00.
106272130.9% has been its average CPU usage since then, or 213504d00h/4h49m
```
That is with px from Debian/unstable, so 1.0.32.

Best

Norbert

**Comment by walles** [comment]
Can you post the output of `ps -ax -o 'pid,ppid,lstart,uid,pcpu,time,%mem,command'` on your system?

**Comment by norbusan** [comment]
H
sorry, the btrfs process had terminated when I woke up this morning (Japan time). I will remember to collect this info when it happens again. If there isn't anything else I can do, feel free to close the report.

**Comment by walles** [comment]
I wasn't actually after one with your btrfs process in it (even though that would have been super!), I just wanted to see if your output is different from what `px` expects somehow.

Maybe your system is set up in some way I never expected, that would explain why `px` fails here.

And to avoid locale problems (this is what `px` does internally):
```bash
LANG= ps -ax -o 'pid,ppid,lstart,uid,pcpu,time,%mem,command'
```

**Comment by norbusan** [comment]
Hi @walles 
ok, that is easy, here are a few entries
```
   2411       1 Mon May 25 21:30:49 2020  1000  0.0 00:00:00  0.0 kdeinit5: Running...
   2432    2382 Mon May 25 21:30:49 2020  1000  0.0 00:00:11  0.1 /usr/lib/mozc/mozc_server
   2443    2411 Mon May 25 21:30:52 2020  1000  0.0 00:00:04  0.0 /usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher --fd=9
   2446    2411 Mon May 25 21:30:52 2020  1000  0.0 00:00:19  0.1 kded5
   2458    2411 Mon May 25 21:30:52 2020  1000  0.0 00:00:05  0.0 /usr/bin/kaccess
   2463    2304 Mon May 25 21:30:52 2020  1000  0.0 00:00:00  0.0 /usr/bin/plasma_session
   2466    2250 Mon May 25 21:30:52 2020  1000  0.0 00:00:01  0.0 /usr/libexec/dconf-service
   2476       1 Mon May 25 21:30:52 2020  1000  0.0 00:00:12  0.0 /usr/bin/ksmserver
   2485    2250 Mon May 25 21:30:52 2020  1000  0.0 00:00:07  0.0 /usr/bin/kglobalaccel5
   2506    2476 Mon May 25 21:30:52 2020  1000  3.4 00:52:54  0.3 /usr/bin/kwin_x11 -session 10c6e4d36c000158448232000000
   2511       1 Mon May 25 21:30:52 2020  1000  0.9 00:14:08  1.3 /usr/bin/plasmashell
```

I never had problems and normally values shown are also correct.

Thanks

**Comment by walles** [comment]
I suspect the `TIME` column on your system might behave differently from the same column on mine, when the CPU time exceeds 24h. Or that the whole line parses differently than what I expect under certain circumstances.

Can you post the full output of this so I can see if any process seems to stand out?
```
LANG= ps -ax -o 'pid,ppid,lstart,uid,pcpu,time,%mem,command'
```

For reference, here's my longest running process (312h):
```
  287     1 Sun Apr 12 19:00:22 2020        88   3.9 312:15.77  1.5 /System/Library/PrivateFrameworks/SkyLight.framework/Resources/WindowServer -daemon
```

Unit tests for time parsing are here:
https://github.com/walles/px/blob/python/tests/px_process_test.py#L94

**Comment by walles** [comment]
@norbusan, can you post the full output of `LANG= ps -ax -o 'pid,ppid,lstart,uid,pcpu,time,%mem,command'` on your machine so I can see if any process seems to stand out?

**Comment by norbusan** [comment]
Hi @walles 
I completely forgot about this item. As said, after the one case I couldn't reproduce it at all. In the near future I will replace a disk in my btrfs array and will rerun btrfs balance, which will probably run for lots of hours. I will try to check what is going on then.

Now, there is nothing strange here, all fine, all the process are displayed without any hiccups, so posting ps lists won't be really helpful.

I think we can close the issue for now, and in case something similar happens, I will reopen and provide the details you asked for.

Thanks

Norbert

**Comment by walles** [comment]
Cool!

If you *do* get this problem again, do provide the *complete* output of `LANG= ps -ax -o 'pid,ppid,lstart,uid,pcpu,time,%mem,command'`.

Closing for now.
