### ISSUE TITLE
Make memory usage take swap into account on macOS

### ISSUE THREAD

**Issue by walles** [walles/px#80]
On macOS, we don't include swap file size in the memory usage.

This is because I don't know how.

Asked here: <https://apple.stackexchange.com/questions/400010>

Once that has been answered, fix here:
<https://github.com/walles/px/blob/24ba75fd640cca9f792e8f8216aee5a0fabbb770/px/px_meminfo.py#L262-L265>

**Comment by jksoegaard** [comment]
You can get the current swap usage on the command line by running the following command:

`sysctl vm.swapusage`

It will output something similar to:

`vm.swapusage: total = 4096.00M  used = 2743.50M  free = 1352.50M  (encrypted)`

**Comment by walles** [comment]
Fixed by f5b0bb851ab4e09fab4e61c97ec77d98f1d75883.

**Comment by walles** [comment]
Released in 1.0.36.
