### ISSUE TITLE
Homebrew depends_on or uses_from_macos "lsof"?

### ISSUE THREAD

**Issue by ritzmann** [walles/px#86]
`brew audit` suggests to replace `depends_on "lsof"` with `uses_from_macos "lsof"` in px.rb. Will that work or does `px` depend on some specific features provided by the external lsof?

**Comment by walles** [comment]
Any `lsof` should do!

Upside with `depends_on` is that I'm guessing that would work on Linux as well, but for now homebrew Linux is a secondary concern.

And if homebrew Linux support would become a primary concern at some point, the formula could always be updated later.

Go for `uses_from_macos`!

**Comment by ritzmann** [comment]
Submitted with `uses_from_macos`.
