### ISSUE TITLE
Typos discovered by codespell

### ISSUE THREAD

**Issue by cclauss** [walles/px#92]
% [`codespell --count --ignore-words-list=iterm,nd`'(https://pypi.org/project/codespell/)
```
./px/px/px_terminal.py:46: Tread ==> Thread, treat
./px/px/px_terminal.py:57: occured ==> occurred
./px/px/px_top.py:62: substract ==> subtract
./px/px/px_top.py:85: substract ==> subtract
./px/px/px_top.py:89: substract ==> subtract
./px/doc/DESIGN.md:6: useable ==> usable
```

**Comment by walles** [comment]
Your first suggestion would actually break the text, the expression is "Tread carefully" and nothing else.

Fixed the other ones.

TIL that "useable" is actually an OK spelling in US English, but not the most common one.
