### ISSUE TITLE
Suggestion: Optionally limit number of `launched binaries` rows

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [walles/px#98]
**SITUATION**: `ptop` is a very usefully modernized take on the Unix `top` program

![A typical readout of process activity in the ptop program](https://user-images.githubusercontent.com/850082/170167756-2885d782-57d4-48bb-bd29-7fd61bd3af01.png)

It even comes with a feature that counts the number of times various binaries have launched since `ptop` began running

![A readout of ptop with two rows of output displaying launched binaries](https://user-images.githubusercontent.com/850082/170167956-0a4b36b4-4465-427c-b3e1-70b69baf4a30.png)

But these launched binary details can start to be a bit much...

![Screen Shot 2022-05-24 at 7 26 12 518 PM](https://user-images.githubusercontent.com/850082/170168195-09586453-76c0-4917-b3e6-0db94f53a2a4.png)

It turns out, a lot of binaries tend to launch in modern operating systems!

![Screen Shot 2022-05-24 at 7 27 35 154 PM](https://user-images.githubusercontent.com/850082/170168302-68496bca-f5c8-42d7-84ff-c56b8442d36b.png)

But although the launched binary details eventually fill many rows, the information within those rows tends to remain largely static. Despite this, there's no means of clearing the launched binary details and returning those rows to the process detail list.

**PROPOSAL**: There are many ways this experience could improve. One possibility is to allow the user to set a maximum number of rows to be used for launched binary details. Another is to allow the user to clear the launched binaries list via keystroke, or to toggle the launched binaries panel with the same. I love using ptop, and would love it even more if this quirk didn't force me to quit and relaunch it when I open as few as three (3) apps.

Thank you for reading this!
The Peoples' Bourgeois

**Comment by walles** [comment]
Thanks for the detailed report, and the screenshots!

The current layout algorithm is to [give the CPU top list at least 10 lines](https://github.com/walles/px/blob/c9eb06102aab7bbf1ba450db50c3f4c89b9f2e76/px/px_top.py#L231), after which [the launches section gets the leftovers](https://github.com/walles/px/blob/c9eb06102aab7bbf1ba450db50c3f4c89b9f2e76/px/px_top.py#L262).

But maybe a better algorithm would be to give the launches section at most 30% of the lines, and then give the rest to the CPU top list?

I think it starts getting too much about here, and I'm guesstimating this to 40%. With at-most-30% we'd never get to this point:

![Screen Shot 2022-05-24 at 7 26 12 518 PM](https://user-images.githubusercontent.com/850082/170168195-09586453-76c0-4917-b3e6-0db94f53a2a4.png)

What do you think?

**Comment by walles** [comment]
This is what it looks like with at-most-25-percent used by the launches section.
<img width="997" alt="max-25-percent" src="https://user-images.githubusercontent.com/158201/170491014-d6bd362a-e3ce-4600-9c65-f25a836ed611.png">

**Comment by thepeoplesbourgeois** [comment]
Thank you for the compliment! I think allowing binary launch tracking to use up to 30% of the available lines would probably strike the best balance of usability for that information and the process list. That being said, I don't know if I'm the target audience for that feature, so it might be good to get feedback from people who've engaged with it more than I have.

**Comment by walles** [comment]
Just kicked off the Homebrew PR for a release with this change in it: https://github.com/Homebrew/homebrew-core/pull/102479
